<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Find jobs</name>
   <tag></tag>
   <elementGuidId>4edb5e16-a9a1-45f5-8f7d-71c59ed5d39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.yosegi-InlineWhatWhere-primaryButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43b3f174-0b8e-4cb5-ba0b-283bc788a423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yosegi-InlineWhatWhere-primaryButton</value>
      <webElementGuid>d0d2ba7b-dfb6-4240-ac06-e2bd491b82ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dafd396a-6515-4b9a-a527-10dacdbe2f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find jobs</value>
      <webElementGuid>1ed9c2be-dffb-4789-a279-fac469c4f071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobsearch&quot;)/button[@class=&quot;yosegi-InlineWhatWhere-primaryButton&quot;]</value>
      <webElementGuid>1c416ae5-36c6-40c3-a0a7-08aad0397342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>c5e40765-fe66-4c87-b481-5959adcdc22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='jobsearch']/button</value>
      <webElementGuid>358258b9-cada-4037-85ad-32dda14ea708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where'])[1]/following::button[1]</value>
      <webElementGuid>8445fa3b-e51d-4020-b72d-4a4392a46eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What'])[1]/following::button[1]</value>
      <webElementGuid>eae7bf4f-2ca4-4679-a37b-04654ab646a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post your resume'])[1]/preceding::button[1]</value>
      <webElementGuid>690c8fbc-52ed-40c1-a398-2b81a7336ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/preceding::button[1]</value>
      <webElementGuid>70bb1040-cf74-4564-b80a-9a6af466f234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>acbdb2bc-1f2c-4704-99b6-c60953a24157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Find jobs' or . = 'Find jobs')]</value>
      <webElementGuid>d04f59b4-0730-4684-bbe1-b67271822897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
